name: Build Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v3

      - name: Update latest file
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            try {
              const fs = require('fs');
              const data = JSON.parse(fs.readFileSync('./launcher/json/version.json'));
              const versionName = `${data.reserved}.${data.major}.${data.minor}.${data.revision}`;
              fs.writeFileSync('./launcher/latest', `https://github.com/MCSR-Ranked/Launcher/releases/download/v${versionName}/MCSRRankedLauncher-${versionName}.exe`, 'utf8');
            } catch(err) {
              core.error("Error while reading or parsing the JSON")
              core.setFailed(err)
            }

      - name: Move directory
        run: |
          to_move=$(echo *)
          mkdir -p _site/v1
          mv $to_move _site/v1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}